name: rieu
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  cloud_firestore: ^5.2.1
  firebase_auth: ^5.1.4
  firebase_core: ^3.3.0
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  formz: ^0.7.0
  go_router: ^14.2.3
  google_sign_in: ^6.2.1
  provider: ^6.1.2
  url_launcher: ^6.3.0

dev_dependencies:
  change_app_package_name: ^1.3.0
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/data/
